export const demoRecords = [
  {
    id: 'demo-1',
    serial: '001AE8F7918F',
    modelo: 'iPhone 13 128GB',
    estado: 'INSTALADO',
    cliente: 'Hotel Costa Norte',
    ubicacion: 'Lobby - Rack principal',
    tecnico: 'Luis Duarte',
    fechaAlta: '2026-03-20T09:10:00.000Z',
    fechaUltimoMovimiento: '2026-03-20T09:10:00.000Z',
    observaciones: 'Equipo operativo y entregado a recepción.',
    fuenteCaptura: 'camara',
    historial: [
      {
        id: 'demo-1-mov-1',
        tipo: 'alta',
        estado: 'INSTALADO',
        modelo: 'iPhone 13 128GB',
        cliente: 'Hotel Costa Norte',
        ubicacion: 'Lobby - Rack principal',
        tecnico: 'Luis Duarte',
        observaciones: 'Equipo operativo y entregado a recepción.',
        fuenteCaptura: 'camara',
        fecha: '2026-03-20T09:10:00.000Z',
      },
    ],
  },
  {
    id: 'demo-2',
    serial: '001AE8F79C13',
    modelo: 'Samsung Galaxy A54',
    estado: 'DESINSTALADO',
    cliente: 'Clínica Central',
    ubicacion: 'Almacén móvil',
    tecnico: 'Ana Pérez',
    fechaAlta: '2026-03-21T14:30:00.000Z',
    fechaUltimoMovimiento: '2026-03-21T14:30:00.000Z',
    observaciones: 'Pendiente de instalación en próxima visita.',
    fuenteCaptura: 'manual',
    historial: [
      {
        id: 'demo-2-mov-1',
        tipo: 'alta',
        estado: 'DESINSTALADO',
        modelo: 'Samsung Galaxy A54',
        cliente: 'Clínica Central',
        ubicacion: 'Almacén móvil',
        tecnico: 'Ana Pérez',
        observaciones: 'Pendiente de instalación en próxima visita.',
        fuenteCaptura: 'manual',
        fecha: '2026-03-21T14:30:00.000Z',
      },
    ],
  },
  {
    id: 'demo-3',
    serial: '001AE8FBDDED',
    modelo: 'Motorola G84',
    estado: 'AVERIADO',
    cliente: 'Residencial Laguna',
    ubicacion: 'Caja técnica exterior',
    tecnico: 'Marta León',
    fechaAlta: '2026-03-22T11:45:00.000Z',
    fechaUltimoMovimiento: '2026-03-22T11:45:00.000Z',
    observaciones: 'No enciende tras corte eléctrico.',
    fuenteCaptura: 'camara',
    historial: [
      {
        id: 'demo-3-mov-1',
        tipo: 'alta',
        estado: 'AVERIADO',
        modelo: 'Motorola G84',
        cliente: 'Residencial Laguna',
        ubicacion: 'Caja técnica exterior',
        tecnico: 'Marta León',
        observaciones: 'No enciende tras corte eléctrico.',
        fuenteCaptura: 'camara',
        fecha: '2026-03-22T11:45:00.000Z',
      },
    ],
  },
];
